### ISSUE TITLE
The KinectDebugWIndow seems to add bugs to the program pretty easily. Investigate and fix this problem.

### ISSUE THREAD

**Issue by jawaff** [WaffleTime/KinectController#10]
The problems seem to have to do with thread safety and some exceptions that are being thrown. If the debug window would run using a separate UserTracker than the KinectUserTracker class, then there'd be lots of AWT-asdfasdf nullpointerexceptions messages. After making it so that both classes use the same UserTracker, then the debug window wouldn't update very often.

**Comment by jawaff** [comment]
When the two classes share the UserTracker there's also an exception that might be getting thrown when a user is starting to be tracked? The debug window isn't able to draw the skeleton of the user because the user isn't having its skeleton being tracked probably.

Exception in thread "Thread-647" java.lang.NullPointerException
        at com.lcsc.hackathon.kinectcontroller.kinect.KinectUserTracker.onNewFrame(KinectUserTracker.java:118)
        at com.primesense.nite.UserTracker.onFrameReady(UserTracker.java:289)

**Comment by jawaff** [comment]
It was a stupid bug. Basically I was telling the UserTracker to start the skeleton tracking on the user id, -1. I was getting the actual user id after I started the skeleton tracking. The UserTracker didn't want to track a non-existent user.
